<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="css/styles.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="website icon" type="png" href="images/BookBerries-logo.png" />
    <script src="script.js" language="javascript"></script>
</head>

<body>
<nav class="navbar navbar-expand-sm bg-white sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="index.php" ><img src="images/BookBerries-logo.png"
                    style="height: 200px;"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php" >Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="about.php" >About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.php" >Contact</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            My Account
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="Login.php" >Sign-In</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="Logout.php" >Logout</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="MyOrders.php" ><i
                                class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="text" id="txtSearch" placeholder="Search">
                    <button class="btn btn-primary" type="button">Search</button>
                </form>
            </div>
        </div>
</nav>
    <center><img src="images/privacy policy.png" style="width:60%; height:500px;"></center>
    <div class="divider d-flex type">
        <h3 class="mx-3 mb-0 or">PRIVACY, STATUTORY RIGHTS AND COOKIE POLICY</h3>
    </div>
    <center>
        <div id="watermill-intro">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 editable" id="privacy-region-2">
                        <p>The following Terms and Conditions do not affect your statutory rights as a consumer.
                            Terms Of
                            Use By accessing, browsing, or using this site, you acknowledge that you have read,
                            understood,
                            and agree to be bound by these terms.
                        </p>
                        <div class="divider d-flex">
                            <h3 class="mx-3 mb-0 or">About Us</h3>
                        </div><br>
                        <p>BookBerries is dedicated to your total satisfaction. If you have any suggestions or
                            comments
                            please
                            contact us
                            BookBerries Bookshop<br>
                            Tel: <a href="tel:81 414 537">81 414 537</a><br>
                            Email: <a href="mailto:BookBerries@gmail.com">BookBerries@gmail.com</a>
                        </p>
                        <p>Cookies Cookies are small text files that help your browser navigate through a website.
                            The
                            cookie file is generated by the site you're browsing and is accepted and processed by your
                            computer's browser software. The cookie file is stored in your browser's folder or
                            subfolder.
                            Your browser accesses the cookie file again when you visit the website that created the
                            cookie
                            file. The browser uses the information stored in the cookie file to help ease your
                            navigation of
                            the website by letting you log in automatically or remembering settings you selected during
                            your
                            earlier visits to the website, among many other functions. Any particular website cannot
                            access
                            information on your computer other than the cookie it set on your computer. The cookie
                            is not
                            executable code so it doesn't have any 'life' of its own other than being used by the
                            website
                            that created it. As explained above, such use is limited to helping your browser process
                            the
                            information located on the website. What do we use cookies for? We use analytics
                            software
                            provided by Google, which sets a number of cookies with varying life spans up to 2
                            years. The
                            service provides anonymous information about site visitors, for example whether a visitor
                            arrived directly or via a search engine.
                        </p><br>
                        <div class="divider d-flex">
                            <h3 class="mx-3 mb-0 or">What happens if you block or reject our cookies?</h3>
                        </div><br>
                        <img src="images/cookies.png" style="width: 600px; height: 400px;"><br><br>
                        <p> If you choose to block our cookies, you will not be able to add items to your shopping
                            basket,
                            proceed to checkout, or use any account features that require you to sign in. Because
                            cookies
                            allow you to take advantage of essential features of this website, we recommend that you
                            leave
                            them turned on. If you do leave cookies turned on, be sure to sign off when you finish,
                            especially when using a shared computer. How you can manage cookies The Help menu in
                            most
                            common
                            browsers will tell you: How to prevent your browser from accepting new cookies; How to have
                            the
                            browser notify you when you receive a new cookie ; How to disable cookies altogether.
                        </p><br>
                        <div class="divider d-flex type">
                            <h3 class="mx-3 mb-0 or">PRIVACY POLICY</h3>
                        </div><br>
                        <p>Owl Bookshop Limited (trading as The Watermill, Homer, BookBerries Bookshop) is committed to
                            ensuring
                            that your privacy is protected. This policy explains how we use the information we
                            collect
                            about
                            you and the procedures that we have in place to safeguard your privacy whilst you use the
                            website.
                        </p>
                        <p>We will only use the information that we collect about you lawfully (in accordance with the
                            Data
                            Protection Act 1998 and GDPR 2018). The Information We Collect and How We Use It If you
                            subscribe to our mailing lists we may use your information to tell you about any special
                            offers,
                            author signings, and other events or features of our website which we think may be of
                            interest
                            to you (and for related marketing purposes).
                        </p>
                        <p> By submitting your information, you consent to the use of that information as set out in
                            this
                            Policy. If we change our Privacy Policy we will post the changes on this page so that
                            you
                            may be
                            aware of them. Opt Out If you wish to stop receiving some or all of the information that
                            we
                            currently send, you may amend or remove your preferences by clicking on the unsubscribe link
                            at
                            the bottom of your emails and following the instructions provided. Security of Your
                            Information
                            We follow strict security procedures in the storage and disclosure of information which you
                            have
                            given us. This is to prevent unauthorised access or unlawful processing of your personal
                            information. We keep your information confidential and store it on a secure server which
                            is
                            password protected and hidden behind a firewall from the outside world. We use secure
                            socket
                            layer software (SSL) to encrypt all of your personal information. Non-disclosure To
                            Third
                            Parties We use your information only as set out in this Policy and will not sell, rent, or
                            pass
                            your information on to others for marketing purposes without your consent.
                        </p>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </center><br>
    <footer class="text-center text-lg-start text-dark foot bg-light">
        <section class="d-flex justify-content-center p-4 text-dark border-bottom connect ">
            <div class="me-5">
                <span>Get connected with us on social networks:</span>
            </div>
            <div class="media">
                <a href="https://www.facebook.com/profile.php?id=100063305825552&mibextid=ZbWKwL" target="_blank"
                    class="text-dark me-4">
                    <i class="fa fa-facebook-f"></i>
                </a>
                <a href="" class="text-dark me-4">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="" class="text-dark me-4">
                    <i class="fa fa-google"></i>
                </a>
                <a href="https://instagram.com/book_berries__?igshid=MmJiY2I4NDBkZg==" target="_blank"
                    class="text-dark me-4">
                    <i class="fa fa-instagram"></i>
                </a>
            </div>
        </section>
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold type">BookBerries</h6>
                        <hr>
                        <p>BookBerries offers a huge collection of books from diverse categories of Fiction,
                            Non-fiction,
                            Biographies, Self-Help, etc.</p>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold type">Products</h6>
                        <p>
                            <a href="index.php #newReleases" class="text-dark">New Releases</a>
                        </p>
                        <p>
                            <a href="index.php #best" class="text-dark">Bestsellers</a>
                        </p>
                        <!-- <p>
                            <a href="index.php #collection" class="text-dark">Collections</a>
                        </p> -->
                        <p>
                            <a href="index.php #accessories" class="text-dark">Accessories</a>
                        </p>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold type">About</h6>
                        <p>
                            <a href="index.php" target="_blank" class="text-dark">Home</a>
                        </p>
                        <p>
                            <a href="about.php" target="_blank" class="text-dark">About Us</a>
                        </p>
                        <p>
                            <a href="privacypolicy.php" target="_blank" class="text-dark">Privacy Policy</a>
                        </p>
                        <p>
                            <a href="contact.php" target="_blank" class="text-dark">Contact Us</a>
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold type">Contact</h6>
                        <p><i class="fa fa-home me-3"></i> Beirut, Down Town, Lebanon</p>
                        <p>
                            <i class="fa fa-envelope me-3"></i>
                            BookBerries@gmail.com
                        </p>
                        <p><i class="fa fa-phone me-3"></i> + 961 81 414 537</p>
                        <p><i class="fa fa-print me-3"></i> + 961 1 414 538</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Copyright -->
        <div class="text-center p-3 Copyright">
            © 2023 Copyright:
            <a class="type" href="index1.php">BookBerries.com</a>
        </div>
    </footer>
</body>

</html>